---
- name: Check disk usage on all hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Run df -h to check disk usage
      shell: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
